import 'C:/Users/Abela/Pictures/Spotify/spotify/styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <title>Spotify</title>
      <body>{children}</body>
    </html>
  )
}
